[[headers]]
  for = "/*"
  [headers.values]
   Cross-Origin-Resource-Policy = 'cross-origin'
   Cross-Origin-Embedder-Policy = 'require-corp'

[build.environment]
  NPM_CONFIG_USERCONFIG = "./netlify/.npmrc"
