[[headers]]
  for = "/*"
  [headers.values]
   Cross-Origin-Resource-Policy = 'cross-origin'
   Cross-Origin-Embedder-Policy = 'credentialless'
   Cross-Origin-Opener-Policy = 'same-origin'

[build.environment]
  NPM_CONFIG_USERCONFIG = "./netlify/.npmrc"
